feat(VIPER-56_57): add API login, register, forgot"
bxthien/ojt-final-project pull request #16
Opened 2024-11-20 15:42 UTC by hthh03

2024-11-21 06:49 UTC, bxthien requested changes

2024-11-21 06:49 UTC, bxthien commented on src/locales/vi.json
> +    "success": {
move success outside same line with login, dont using 1 variable many time

2024-11-21 06:49 UTC, bxthien commented on src/locales/vi.json
> +    "error": {
fix like above

2024-11-22 03:13 UTC, thienbuidev approved these changes

2024-11-22 03:14 UTC, thienbuidev approved these changes

2024-11-22 03:14 UTC, bxthien approved these changes

2024-11-22 03:14 UTC, merged