feat(VIPER-86): design the shopping cart interface
bxthien/ojt-final-project pull request #6
Opened 2024-11-19 03:41 UTC by Tatchuong

2024-11-19 04:45 UTC, thienbuidev requested changes

2024-11-19 04:45 UTC, thienbuidev commented on src/components/SelectAdress/AddressCard.tsx
> +        border: isSelected ? '2px solid #4CAF50' : '1px solid #ddd',
using className

2024-11-19 04:45 UTC, thienbuidev commented on src/components/SelectAdress/AddressCard.tsx
> +      <div style={{ flex: 1, marginRight: '20px' }}>
className

2024-11-19 04:45 UTC, thienbuidev commented on src/components/SelectAdress/AddressCard.tsx
> +              padding: '4px 8px',
className

2024-11-19 04:45 UTC, thienbuidev commented on src/components/SelectAdress/AddressCard.tsx
> +        <p style={{ margin: '5px 0', color: '#666', fontSize: '14px' }}>{address.address}</p>
className

2024-11-19 04:45 UTC, thienbuidev commented on src/components/SelectAdress/AddressCard.tsx
> +        style={{ marginRight: '20px', cursor: 'pointer', width: '18px', height: '18px' }}
className

2024-11-19 04:45 UTC, thienbuidev commented on src/components/SelectAdress/AddressCard.tsx
> +            background: 'none',
className

2024-11-19 04:45 UTC, thienbuidev commented on src/components/SelectAdress/AddressCard.tsx
> +          style={{
className

2024-11-19 07:31 UTC, bxthien requested changes

2024-11-19 07:31 UTC, bxthien commented on src/components/SelectAdress/AddressCard.tsx
> +const AddressCard = ({
using interface

2024-11-19 08:18 UTC, bxthien requested changes

2024-11-19 08:18 UTC, bxthien commented on src/components/SelectAdress/AddressCard.tsx
> +      <input
using Input Ant design

2024-11-19 08:18 UTC, bxthien commented on src/components/SelectAdress/AddressCard.tsx
> +        <button
using Button Ant design

2024-11-19 08:18 UTC, bxthien commented on src/components/payments/Cart.tsx
> +          <tr>
using table

2024-11-20 04:23 UTC, thienbuidev approved these changes

2024-11-20 07:05 UTC, thienbuidev approved these changes

2024-11-20 07:06 UTC, thienbuidev approved these changes

2024-11-20 07:07 UTC, thienbuidev approved these changes

2024-11-20 07:08 UTC, bxthien approved these changes

2024-11-20 07:08 UTC, merged