feat(Viper 92,94): add the payment interface, choose payment method
bxthien/ojt-final-project pull request #7
Opened 2024-11-19 07:00 UTC by tran-duy2

2024-11-19 07:17 UTC, thienbuidev requested changes

2024-11-19 07:17 UTC, thienbuidev commented on src/pages/shipping.tsx
> +            <select
Try using real data city

2024-11-19 07:17 UTC, thienbuidev commented on src/pages/shipping.tsx
> +              <option>Province</option>
try using real data

2024-11-19 07:17 UTC, thienbuidev commented on src/pages/shipping.tsx
> +            <input
Using Form.Item > Input of Ant Design.

2024-11-19 07:17 UTC, thienbuidev commented on src/pages/payment.tsx
> +                  {cardFormVisible && (
try seperate new component

2024-11-19 07:17 UTC, thienbuidev commented on src/pages/payment.tsx
> +              {showPaymentDetails && (
try to new component

2024-11-25 14:29 UTC, bxthien approved these changes

2024-11-25 14:34 UTC, bxthien approved these changes

2024-11-25 14:38 UTC, bxthien approved these changes

2024-11-25 14:40 UTC, thienbuidev approved these changes

2024-11-25 14:40 UTC, merged